# This is a prebuilt Docker container that contains all of the dependencies.
# It is prebuilt to speed up continuous integration.
# The Dockerfile is stored on the 'docker' branch.
image: containers.ligo.org/leo-singer/ligo.skymap

stages:
  - test
  - deploy

test:
  variables:
    CFLAGS: -coverage
  script:
    # Run tests
    - python3 setup.py test --coverage -vv --args='-vv'
    # Write gcovr test coverage
    - mkdir gcovr
    - gcovr build/temp*/src -r . --html --html-detail -o gcovr/index.html
    # Generate docs
    - python3 setup.py build_docs
  artifacts:
    paths:
      - .coverage
      - build/temp.*/src/*.gc*
      - gcovr/
      - htmlcov/
      - docs/_build/html
    expire_in: 5 minutes

coverage:c:
  variables:
    GIT_STRATEGY: none
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  stage: deploy
  script:
    # Display coverage summary
    - gcovr build/temp*/src -r .

coverage:py:
  variables:
    GIT_STRATEGY: none
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  stage: deploy
  script:
    # Print coverage summary
    - python3 -m coverage report

pages:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - mv docs/_build/html public
    - mkdir -p public/cov
    - mv gcovr public/cov/c
    - mv htmlcov public/cov/py
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
