image: ligo/builder:el7

stages:
  - test

cache:
  paths:
    - yum-cache
    - pip-cache
    - .eggs

before_script:
  # Configure yum cache
  - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
  - sed -i 's|cachedir=.*|cachedir='$(pwd)'/yum-cache|' /etc/yum.conf
  - mkdir -p yum-cache
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    # Install dependencies
    - yum install -y python-pip lalinference-python
    - pip install --upgrade setuptools
    - pip install pytest-cov
    # Run tests
    - python setup.py test -vv --cov
