image: ligo/lalsuite-dev:stretch

stages:
  - test
  - deploy

cache:
  paths:
    - pip-cache
    - .eggs

before_script:
  # Configure apt
  - apt-get update -qq
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

test:
  variables:
    CFLAGS: -coverage
  script:
    # Install dependencies
    - apt-get -y -qq install gcovr lal-python lal-python3 lalsimulation-python3 libchealpix-dev libgsl-dev pkg-config python-glue-ligolw-tools python3-astropy python3-astropy-helpers python3-glue python3-h5py python3-healpy python3-matplotlib python3-pil python3-pip python3-pytest python3-pytest-cov python3-reproject python3-scipy python3-shapely python3-six python3-sphinx
    # Run tests
    - python3 setup.py test -vv --coverage
    # Write gcovr test coverage
    - mkdir gcovr
    - gcovr build/temp*/src -r . --html --html-detail -o gcovr/index.html
  artifacts:
    paths:
      - build/temp.*/src/*.gc*
      - gcovr/
      - htmlcov/
    expire_in: 5 minutes

coverage:c:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  stage: deploy
  script:
    # Install dependencies
    - apt-get -y -qq install gcovr
    # Display coverage summary
    - gcovr build/temp*/src -r .

coverage:py:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  stage: deploy
  script:
    # Install dependencies
    - apt-get -y -qq python3-coverage
    # Print coverage summary
    - python3 -m coverage report

pages:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - mkdir -p htmlcov
    - mv gcovr htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
