image: ligo/builder:stretch

stages:
  - test

cache:
  paths:
    - pip-cache
    - .eggs

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # Configure apt
  - apt-get update -qq
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    # Install dependencies
    - apt-get -y -qq install libchealpix-dev libgsl-dev pkg-config python3-astropy python3-h5py python3-healpy python3-matplotlib python3-pil python3-pip python3-scipy python3-six python3-six
    - pip3 install --upgrade setuptools
    - pip3 install pytest-cov
    # Run tests
    - python3 setup.py test -vv --cov
