name: ligo.skymap
dependencies:
  - python=3.7
  - astropy
  - h5py
  - gsl
  - matplotlib
  - networkx
  - numpy
  - pillow
  - pkg-config
  - scipy
  - seaborn
  - tqdm
  - pytz
  - pip:
    - sphinx-argparse
    - sphinx-astropy
    - -r requirements.txt
